---
# file: ansible.yml
- hosts: all
  become: true
  tasks:
    - name: ansible ppa
      apt_repository:
        repo:  ppa:ansible/ansible
        state: present
    - name: install ansible
      apt:
        name:  ansible
        state: present
